CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(240), email VARCHAR(240), password VARCHAR(240));

CREATE TABLE peeps(id SERIAL PRIMARY KEY, body VARCHAR(280), date DATE, user_id INTEGER REFERENCES users (id));
