
CREATE DATABASE chitter

CREATE TABLE posts(id SERIAL PRIMARY KEY, Msg VARCHAR(60));

ALTER TABLE posts ADD COLUMN TimeAdded VARCHAR(60);

CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(60));

ALTER TABLE users ADD COLUMN password VARCHAR(60);
