CREATE TABLE users(id SERIAL PRIMARY KEY, email VARCHAR(120) UNIQUE, password VARCHAR(120), name VARCHAR(120), username VARCHAR(120) UNIQUE);
CREATE TABLE peeps(id SERIAL PRIMARY KEY, text VARCHAR(160), user_id INTEGER REFERENCES users (id));
ALTER TABLE peeps ADD COLUMN created_at TIMESTAMP;
ALTER TABLE peeps ALTER COLUMN created_at SET DEFAULT now();
