CREATE TABLE users(id SERIAL PRIMARY KEY, username VARCHAR(60), password VARCHAR(60), name VARCHAR(60), email TEXT);
CREATE TABLE peeps(id SERIAL PRIMARY KEY, name VARCHAR(60), username VARCHAR(60), peep VARCHAR(60), ts TIMESTAMPTZ DEFAULT 'Now()');
