CREATE TABLE peeps(id SERIAL PRIMARY KEY, peep VARCHAR(280));
ALTER TABLE peeps ADD COLUMN time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE peeps ADD COLUMN users_id INTEGER REFERENCES users (id);


CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(50), email VARCHAR(50));