CREATE TABLE chitter;

CREATE TABLE  users (
  ID BIGSERIAL NOT NULL PRIMARY KEY,
  user_name varchar(60),
  password varchar(30)
);

CREATE TABLE  message (
  ID BIGSERIAL NOT NULL PRIMARY KEY,
  ID_USERS INT NOT NULL REFERENCES users(ID),
  message VARCHAR(200),
  createdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);