CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(60), username VARCHAR(60), email VARCHAR(60), password VARCHAR(60),UNIQUE(username, email));
CREATE TABLE peeps(id SERIAL PRIMARY KEY, user_id INT, peep VARCHAR(280), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id));
