CREATE DATABASE chitter;
CREATE TABLE peeps(id SERIAL PRIMARY KEY, message VARCHAR(60));
ALTER TABLE peeps ADD time TIMESTAMP;
ALTER TABLE peeps ADD UserID int;
ALTER TABLE peeps ADD FOREIGN KEY (UserID) REFERENCES users(id);

CREATE DATABASE chitter_test;
CREATE TABLE peeps(id SERIAL PRIMARY KEY, message VARCHAR(60));
ALTER TABLE peeps ADD time TIMESTAMP;
ALTER TABLE peeps ADD UserID int;
ALTER TABLE peeps ADD FOREIGN KEY (UserID) REFERENCES users(id);

