CREATE TABLE peeps(id SERIAL PRIMARY KEY, peep VARCHAR(180));
ALTER TABLE peeps ADD COLUMN created_at TIMESTAMP DEFAULT NOW();


CREATE TABLE users(id SERIAL PRIMARY KEY, email VARCHAR(60), pa
ssword VARCHAR(140));
