CREATE TABLE peeps (
  id SERIAL PRIMARY KEY, 
  body VARCHAR(365) NOT NULL, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
  user_id INT, 
  CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id)
);