CREATE TABLE users(
  user_id serial PRIMARY KEY,
  user_name VARCHAR(50) NOT NULL,
  user_handle VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(350) UNIQUE NOT NULL,
  password VARCHAR(200) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW());
