
CREATE TABLE reply (
  ID BIGSERIAL NOT NULL PRIMARY KEY,
  ID_USERS INT NOT NULL REFERENCES users(ID),
  ID_MESSAGE INT NOT NULL REFERENCES message(ID),
  message VARCHAR(200),
  createdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
