DROP DATABASE IF EXISTS chitter;
DROP DATABASE IF EXISTS chitter_test;
CREATE DATABASE chitter;
CREATE DATABASE chitter_test;
GRANT ALL PRIVILEGES ON DATABASE chitter;
GRANT ALL PRIVILEGES ON DATABASE chitter_test;