DROP DATABASE IF EXISTS chitter;
DROP DATABASE IF EXISTS chitter_test;
DROP ROLE IF EXISTS chitter;
CREATE USER chitter WITH ENCRYPTED PASSWORD 'password';
CREATE DATABASE chitter;
CREATE DATABASE chitter_test;
GRANT ALL PRIVILEGES ON DATABASE chitter TO chitter;
GRANT ALL PRIVILEGES ON DATABASE chitter_test TO chitter;
