CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(40), email VARCHAR(100) UNIQUE, username VARCHAR(60) UNIQUE, password VARCHAR(50));
CREATE TABLE peeps(peep_id SERIAL PRIMARY KEY, text VARCHAR(140), id INTEGER, post_time TIME, FOREIGN KEY(id) REFERENCES users(id));
