class HashedPassword
  attr_accessor id: int

  attr_writer user_id: int

  attr_writer password: string

  public

  def initialize: (id: int, user_id: int, password: string) -> instance

  # TODO Initializes the Hash password class and returns an instance to be used to either create and check a hashed password
  def create: () -> nil

  # TODO creates a hashed password and send that to the database (done at sign up)
  def check: () -> nil

  # TODO checks a hashed password against the database one never storing a password in local

  private

  def retrieve: () -> nil

  # TODO retrieve the password from the database
end
