#frozen_string_literal: true

source "https://rubygems.org"

ruby '2.5.0'

gem 'capybara'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-flash'
gem 'simplecov'
gem 'simplecov-console'
gem 'rubocop'
gem 'pry'
gem 'selenium-webdriver'
gem 'rack'
gem 'pg'
gem 'data_mapper'
