CREATE TABLE peeps(id SERIAL PRIMARY KEY, body VARCHAR(140), date VARCHAR, username VARCHAR);
CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(50), username VARCHAR(20), email VARCHAR(50), password VARCHAR(20));
