# Configure Rubocop to use the config file in the Scaffolint GitHub repo
AllCops:
  Exclude:
    - 'tmp/*'
    - 'secret/*'
    - 'db/**/*.rb'
inherit_from:
  - https://raw.githubusercontent.com/makersacademy/scaffolint/v1.1.0/.rubocop.yml