Metrics/LineLength:
  # We set up error messages here and I don't want people suboptimising by making
  # their variables shorter... so we'll relax this a bit. Usually lines lime this:
  # ```
  #    AIRPORT_REFUSED_MESSAGE = "Airport has refused our landing! Probably bad weather"
  # ```
  # Would get extracted to locales, but that's out of the fence here so.
  Max: 100

  # While test refactoring is good, I suspect it's out of scope for week 1
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  # While test refactoring is good, I suspect it's out of scope for week 1
  Exclude:
    - 'spec/**/*'

# I've been quite careful about which style cops I've enabled
# Why? My feeling is that style cops can create lots of linter noise that
# is hard for a beginner to handle. This focuses the linting onto:
#   * Indentation & whitespace (inconsistency, really gross stuff like `a=1`)
#   * Easy wins in expressiveness (e.g. gurad clauses — nice opportunity to inject concretes)
#   * Egregious non-idiomatic ruby like `def getFilename`
#
# Quote cops are notable by their absence. They add a lot of noise and they're
# annoying to fix so a good opportunity to turn devs off of the utility of
# linting. Hopefully they pick them up later :)

Style/IndentationConsistency:
  Enabled: true
Style/IndentationWidth:
  Enabled: true
Style/AccessorMethodName:
  Enabled: true
Style/BlockEndNewline:
  Enabled: true
Style/ClassAndModuleCamelCase:
  Enabled: true
Style/ConstantName:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/EmptyLineBetweenDefs:
  Enabled: true
Style/EmptyLines:
  Enabled: true
Style/ExtraSpacing:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/IdenticalConditionalBranches:
  Enabled: true
Style/InverseMethods:
  Enabled: true
Style/LeadingCommentSpace:
  Enabled: true
Style/MethodName:
  Enabled: true
Style/NegatedIf:
  Enabled: true
Style/NegatedWhile:
  Enabled: true
Style/NilComparison:
  Enabled: true
Style/Not:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/OneLineConditional:
  Enabled: true
Style/PredicateName:
  Enabled: true
Style/RedundantParentheses:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/SafeNavigation:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/SpaceAfterColon:
  Enabled: true
Style/SpaceAfterComma:
  Enabled: true
Style/SpaceAfterMethodName:
  Enabled: true
Style/SpaceAfterNot:
  Enabled: true
Style/SpaceAfterSemicolon:
  Enabled: true
Style/SpaceAroundBlockParameters:
  Enabled: true
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true
Style/SpaceAroundKeyword:
  Enabled: true
Style/SpaceAroundOperators:
  Enabled: true
Style/SpaceBeforeBlockBraces:
  Enabled: true
Style/SpaceBeforeComma:
  Enabled: true
Style/SpaceBeforeComment:
  Enabled: true
Style/SpaceBeforeFirstArg:
  Enabled: true
Style/SpaceBeforeSemicolon:
  Enabled: true
Style/SpaceInLambdaLiteral:
  Enabled: true
Style/SpaceInsideArrayPercentLiteral:
  Enabled: true
Style/SpaceInsideBlockBraces:
  Enabled: true
Style/SpaceInsideBrackets:
  Enabled: true
Style/SpaceInsideHashLiteralBraces:
  Enabled: true
Style/SpaceInsideParens:
  Enabled: true
Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: true
Style/SpaceInsideRangeLiteral:
  Enabled: true
Style/SpaceInsideStringInterpolation:
  Enabled: true
Style/SymbolLiteral:
  Enabled: true
Style/TrailingBlankLines:
  Enabled: true
Style/TrivialAccessors:
  Enabled: true
Style/VariableName:
  Enabled: true
Style/FileName:
  Enabled: true

# Rubocop doesn't make disabling all cops in a given group easy, so we list...
Style/AccessModifierIndentation:
  Enabled: false
Style/Alias:
  Enabled: false
Style/AlignArray:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/ArrayJoin:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/AsciiIdentifiers:
  Enabled: false
Style/Attr:
  Enabled: false
Style/AutoResourceCleanup:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BeginBlock:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CaseIndentation:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/ClassMethods:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ClosingParenthesisIndentation:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/CommentIndentation:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLineAfterMagicComment:
  Enabled: false
Style/EmptyLinesAroundAccessModifier:
  Enabled: false
Style/EmptyLinesAroundBeginBody:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/EndBlock:
  Enabled: false
Style/EndOfLine:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/FirstArrayElementLineBreak:
  Enabled: false
Style/FirstHashElementLineBreak:
  Enabled: false
Style/FirstMethodArgumentLineBreak:
  Enabled: false
Style/FirstMethodParameterLineBreak:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/FlipFlop:
  Enabled: false
Style/For:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IfUnlessModifierOfIfUnless:
  Enabled: false
Style/IfWithSemicolon:
  Enabled: false
Style/ImplicitRuntimeError:
  Enabled: false
Style/IndentArray:
  Enabled: false
Style/IndentAssignment:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/IndentHeredoc:
  Enabled: false
Style/InfiniteLoop:
  Enabled: false
Style/InitialIndentation:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MultilineArrayBraceLayout:
  Enabled: false
Style/MultilineAssignmentLayout:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineBlockLayout:
  Enabled: false
Style/MultilineHashBraceLayout:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineIfThen:
  Enabled: false
Style/MultilineMemoization:
  Enabled: false
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/MultilineMethodDefinitionBraceLayout:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NestedModifier:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/OpMethod:
  Enabled: false
Style/OptionHash:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantException:
  Enabled: false
Style/RedundantFreeze:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueEnsureAlignment:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/Send:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StringMethods:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/Tab:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/UnneededCapitalW:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/VariableInterpolation:
  Enabled: false
Style/VariableNumber:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
