Layout/IndentArray:
  EnforcedStyle: consistent

Layout/TrailingWhitespace:
  Exclude:
    - 'Rakefile'

Metrics/BlockLength:
  Max: 42

Metrics/LineLength:
  Max: 500

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/app.rb'
    - 'app/models/peep.rb'
    - 'app/models/user.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
