development:
  adapter: postgresql
  encoding: unicode
  database: peep_manager
  pool: 2
  username: Student
  password: makersmac

  production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>