source 'https://rubygems.org'
ruby '2.2.3'

gem 'cucumber'
gem 'coveralls'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rspec'
gem 'rspec-sinatra'
gem 'capybara'
gem 'sinatra'
gem 'database_cleaner'
gem 'rake'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'sanitize'
