source 'https://rubygems.org'
ruby '2.2.3'
gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'pg'
gem 'mailgun-ruby', require: 'mailgun'
gem 'dotenv'
group :test do
  gem 'rspec'
  gem 'cucumber'
  gem 'rubocop-rspec'
  gem 'rubocop'
  gem 'capybara'
  gem 'byebug'
  gem 'factory_girl'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'coveralls', require: false
end
