CREATE DATABASE peeps;
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    author VARCHAR(60)
);
CREATE TABLE peeps (
  id SERIAL PRIMARY KEY,
  link_id INTEGER REFERENCES users(id),
  peep VARCHAR(144)
);
