version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
        
      - run:
          name: Deploy master to heroku
          command: |
            git push https://heroku:fbceac09-fc1f-479d-91f8-31e863d1e6ce@git.heroku.com/ganneys-chitter.git master