 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/peeps", type: :request do
  
  # Peep. As you add validations to Peep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Peep.create! valid_attributes
      get peeps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      peep = Peep.create! valid_attributes
      get peep_url(peep)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_peep_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      peep = Peep.create! valid_attributes
      get edit_peep_url(peep)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Peep" do
        expect {
          post peeps_url, params: { peep: valid_attributes }
        }.to change(Peep, :count).by(1)
      end

      it "redirects to the created peep" do
        post peeps_url, params: { peep: valid_attributes }
        expect(response).to redirect_to(peep_url(Peep.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Peep" do
        expect {
          post peeps_url, params: { peep: invalid_attributes }
        }.to change(Peep, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post peeps_url, params: { peep: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested peep" do
        peep = Peep.create! valid_attributes
        patch peep_url(peep), params: { peep: new_attributes }
        peep.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the peep" do
        peep = Peep.create! valid_attributes
        patch peep_url(peep), params: { peep: new_attributes }
        peep.reload
        expect(response).to redirect_to(peep_url(peep))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        peep = Peep.create! valid_attributes
        patch peep_url(peep), params: { peep: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested peep" do
      peep = Peep.create! valid_attributes
      expect {
        delete peep_url(peep)
      }.to change(Peep, :count).by(-1)
    end

    it "redirects to the peeps list" do
      peep = Peep.create! valid_attributes
      delete peep_url(peep)
      expect(response).to redirect_to(peeps_url)
    end
  end
end
