source 'http://rubygems.org'

ruby '2.2.3'

gem 'bcrypt'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rerun'
gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-partial'

group :test do
  gem 'rspec'
  gem 'rspec-sinatra'
  gem 'capybara'
  gem 'rake'
  gem 'database_cleaner'
  gem 'rubocop'
end
