require './app/models/peep'

describe Peep do

  describe "#time_format" do
    let(:user) { User.create(name: 'Ada Lovelace', user_name: 'Mech01001',email: 'adalove@gmail.com', password: 'LogicLove', password_confirmation: 'LogicLove') }

    it 'makes the time generated by Time.now readable' do
      peep = Peep.create(content: "I'm peeping!", user_id: user.id, created_timedate: Time.now)
      expect(peep.time_format).to eq 
    end

  end

end
