CREATE TABLE peeps
(
  id SERIAL PRIMARY KEY,
  user_id INT,
  peep VARCHAR(60) NOT NULL,
  timestamp VARCHAR(60) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE
);