ALTER TABLE peeps ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
-- ALTER TABLE peeps ADD COLUMN created_at TIMESTAMP;
-- ALTER TABLE mytable ALTER COLUMN created_at DEFAULT GETDATE();
-- ALTER TABLE peeps ADD COLUMN created_at DATETIME NOT NULL DEFAULT(GETDATE();

-- CREATE TABLE Example
-- (
-- SomeField INTEGER,
-- DateCreated DATETIME NOT NULL DEFAULT(GETDATE())
-- )