default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: chitter_development

test:
  <<: *default
  database: chitter_test

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: ec2-54-75-245-94.eu-west-1.compute.amazonaws.com
  port: 5432
