default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development: &development
  <<: *default
  database: chitter_development

test: &test
  <<: *default
  database: chitter_test

production: &production
  <<: *default
<<<<<<< HEAD
  url: <%= ENV['DATABASE_URL'] %>
=======
  url: ENV['DATABASE_URL']
>>>>>>> 85857dab1bbfaef445dbe50dbeb0498ee989d6ee
