default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development: &development
  <<: *default
  database: chitter_development

test: &test
  <<: *default
  database: chitter_test

production: &production
  <<: *default
  database: project_production
  username: project
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
