default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development: &development
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: chitter_development

test: &test
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: chitter_test

production:
    adapter: postgresql
