default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development: &development
  <<: *default
  database: chitter_development

test: &test
  <<: *default
  database: chitter_test

production: &production
  <<: *default
  url: ENV['DATABASE_URL']
