default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  database: chitter_development

test:
  <<: *default
  database: chitter_test

production:
  <<: *default
