- I used CREATE DATABASE to create the chitter databse.
- I used CREATE TABLE to make a table with 6 columns.
- These are: id, peep, time, name, pass and email.
- I then reapeated these steps with a chitter_test database.
- This database is used for rspec tests.