# Generated by cucumber-sinatra. (2015-02-26 19:50:53 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/5hitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = 5hitter

class 5hitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  5hitterWorld.new
end
